# sets up a rtl_tcp server
#
# D. G. Adams 2025-March-13
#
# rtl_tcp, an I/Q spectrum server for RTL2832 based DVB-T receivers
#
#Usage:
#	[-a listen address. must be set. use  0.0.0.0 to listen all]
#	[-p listen port (default: 1234)]
#	[-f frequency to tune to [Hz]]
#	[-g gain (default: 0 for auto)]
#	[-s samplerate in Hz (default: 2048000 Hz)]
#	[-b number of buffers (default: 15, set by library)]
#	[-n max number of linked list buffers to keep (default: 500)]
#	[-d device index (default: 0)]
#	[-P ppm_error (default: 0)]
#	[-T enable bias-T on GPIO PIN 0 (works for rtl-sdr.com v3/v4 dongles)]
#	[-D enable direct sampling (default: off)]

name: rtl-tcp
services:
  rtl-tcp:
    container_name: rtl-tcp
    image: dgadams/rtlsdr4:latest
    restart: unless-stopped
    command: "rtl_tcp -d 1 -a 0.0.0.0 -p 1234"
    devices:
      - /dev/bus/usb
    ports:
      - 1234:1234
    environment:
      - RTL_SERIAL=4
